CREATE TABLE IF NOT EXISTS calendar (
ObjectId INTEGER PRIMARY KEY AUTOINCREMENT,
Name TEXT NOT NULL,
Description TEXT NOT NULL DEFAULT '',
Status INTEGER NOT NULL,
CreateDate DATETIME NOT NULL DEFAULT CURRENT_DATE,
ExecutionDate DATETIME NOT NULL DEFAULT CURRENT_DATE
)